version: 2
updates:
  # Flutter/Dart 의존성 업데이트
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "dart"
    commit-message:
      prefix: "chore"
      include: "scope"
    reviewers:
      - "chad-developers"
    assignees:
      - "chad-developers"

  # GitHub Actions 워크플로우 업데이트
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
    reviewers:
      - "chad-developers"