name: ✨ Feature Request
description: Suggest a new feature for GigaChad Runner
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        # ✨ Feature Request

        Thanks for suggesting a new feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: summary
    attributes:
      label: 📋 Feature Summary
      description: A clear and concise summary of the feature you'd like to see.
      placeholder: Briefly describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🤔 Problem Statement
      description: What problem does this feature solve? What's the pain point?
      placeholder: |
        Is your feature request related to a problem? Please describe.
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution you'd like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives you've considered...

  - type: dropdown
    id: category
    attributes:
      label: 🏷️ Feature Category
      description: What category does this feature belong to?
      options:
        - GPS/Tracking
        - Chad Level System
        - UI/UX Design
        - Statistics/Analytics
        - Social Features
        - Performance
        - Accessibility
        - Settings/Configuration
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: true

  - type: checkboxes
    id: complexity
    attributes:
      label: 🔧 Implementation Complexity (if known)
      description: If you have technical knowledge, estimate the complexity
      options:
        - label: This seems like a simple change
        - label: This might require moderate effort
        - label: This looks like a complex feature
        - label: I'm not sure about the complexity

  - type: textarea
    id: mockup
    attributes:
      label: 🎨 Mockups/Examples
      description: If you have mockups, wireframes, or examples from other apps, please share them here.
      placeholder: Drag and drop images or provide links to examples...

  - type: checkboxes
    id: chad-theme
    attributes:
      label: 💪 Chad Theme Compatibility
      description: Does this feature align with the Chad theme?
      options:
        - label: This feature fits the Chad/motivational theme
        - label: This feature is neutral to the theme
        - label: This feature might not fit the theme (but still valuable)

  - type: textarea
    id: additional
    attributes:
      label: ℹ️ Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
      placeholder: Any additional information...

  - type: checkboxes
    id: terms
    attributes:
      label: ✅ Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided enough detail for the feature to be understood
          required: true
        - label: I understand this is a free and open-source project run by volunteers
          required: true